[GOOGLE_SERVICE_ACCOUNT]
type = "service_account"
project_id = "optipower-project"
private_key_id = "92f918404fff33271d2320324fc428c3b6b49b67"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbXgeHB9v+jrzW
+YdcmCVoPz69ph0A97war4ClNrhyu3Jbo/Roz52ElNEWqQ7AwR1mu4NHCw3f9jXf
i+wlw9hIB/HbxUnj9vV40/JH+a2y2n0RttI8F3RNKSIXzZBYAM78RKVKvuduJeZ4
dE6tQqYTEVFQWvhu9+c4UNNkoxg0YGgoMT50brE3eNdmPtUMdR9iVQVWRyvybJ4P
klpU86SLCWJ2LQudJFI+sKb3LrLCPp2nRtB8xv6ifVzFDCrvLfP4lYA8uk1uunXv
LV03pkRdA2RdqP6efKuM5TOAYenklH9T3xgHlfOM/vwu0ZKqnZMLfG1/8N/zRpH+
/Cc9uAXpAgMBAAECggEAFmS5JQdG+CvOoBWbIwdy7NGg02jr6UXLwPTmz+lRMIg/
9WFuSuURyRhCAsgfLj0nZbVFOKopN8ye+zeJs+/Ebq1meMy417iyrNWvqBweoxbG
zBTTvIGM68ov9cpVMbn8G3QxdtKJPOENlPL+nA5tLXZjh/d0s1nb48wSjADN7k51
dD0lNvd2IQtZiOaNs0Y6tjzXfMkgnNDJza64v9w7X9xOyUehGWhYoJ46iylN9aOF
Gu3moypYg+54mdgpZ49c3W8+GJRbUef0ZtrE8v3vQQ5ncWOKQ/O9L5XWbMPWx7Kh
chTjJIhOMaLoGvZg2c8RiytSsngaad+X/XNvUmc+eQKBgQDLcAXPR0VuiOOi6WwR
Wb196RsvknN4ZJkYnCm1zJX86DRnlq3GF1Z0SF7aDMql09z/sfWwyrU+5gwssGMh
lXtrep/CZcZDrOa6CPqmvbVmgifo1KNB3Hf+/x204lnwZprDnKZKFL/rI2hHhNyy
ZvRFEF/Urcc0lSWFGt9ewE9dnwKBgQDDgn4bwVVaFXlUPmEVtjAtoSGdIhGr6bdf
jN6vTaM3wkc41orcV1ArcjQ6ed6uYDisePLEtt3isH2j2XM7xD1H6jM4Zag2CKK5
7QzUkLyAAMEgXyazuEL5+Uo7R/MsSu6y+EGbOv64MZ8dOYbZbf72b9dUUG8GbdkE
u3nUF/rfdwKBgBeQTyv2HmWyN2O8U8citN8rq/lzpipQxKbkF7S2EL1ti/xfqJsk
QuBPLaVmC+bvRk7bpxCmOh4h+VEH0UOnk9ccKfsTXMaj9UmhFp9Po/5Onx7J2msb
hU6k8CTufupoiA6WS3CTPLOYs1BtZD7JzAtf3Sm+Qy+lAuaK+Up5TfgTAoGBALuM
LpVJfSsRdnZN8Kv3PXhIHgqyZ+lWJkZOyD+6ZlxSzifEBykfyRQkVd3Skr8MJtGs
pJX4JhoT3DKVomku8upNzBzJx/ctiYx5zdkLjwfrsVfwbxvwIq/RaFg9yRQwPZMJ
e0YB7d+cGlramHVzgyW8W//RuO+d6JUVkuTWrB45AoGAZpkDzE/xOZAe3/VUTkkW
rzuSoimxe2RXvGwECu8w88pRfyrtHhcQs7e1p/EgWBsd6hEBoToCplZgKN84vCY5
uZqL61x6eqHcfTQOKa/PmZs0L6XbmNf/LGsEbVYVUUVcdSZTYgj3K5lm/FmQcE7u
gvn7Vl10H5onILEhINSemew=
-----END PRIVATE KEY-----"""
client_email = "optipower-sheet@optipower-project.iam.gserviceaccount.com"
client_id = "114861932500952945187"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/optipower-sheet@optipower-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
